### ISSUE TITLE
pkgConfig breaks build on macOS with MacPorts

### ISSUE THREAD

**Issue by moldabekov** [apple/swift-nio-zlib-support#2]
Hello,
I came here from [grpc-swift](https://github.com/grpc/grpc-swift/).

Today we faced issues with building `grpc-swift` library. After some digging we figured out that issue happens because of conflict between [`pkgConfig`](https://github.com/apple/swift-nio-zlib-support/blob/master/Package.swift#L23) directive and `pkg-config` binary from **MacPorts**. macOS doesn't come bundled with `pkg-config` binary in default installation, but MacPorts provides it.

Also it's well known that macOS ships with it's own version of `zlib`, however there is an external version of `zlib` that comes with some MacPorts packages such as `curl`, `openssl` and so on.

MacPorts `pkg-config` passes `-I/opt/local/include` with `zlib` header files. It's not a surpise that it's incompatible with `zlib` version bundled with macOS itself.

After commenting line [23](https://github.com/apple/swift-nio-zlib-support/blob/master/Package.swift#L23) issue with building has gone. 

I don't exactly know why there is a `pkgConfig` in your `Package.swift` file, although it seems that it's safe to remove it from your package.

P.S For futher information: we've also opened issue https://github.com/grpc/grpc-swift/issues/220 in [grpc-swift](https://github.com/grpc/grpc-swift/) repo.

**Comment by Lukasa** [comment]
There's a `pkgConfig` directive here because we need a way to find zlib on Linux platforms, and this is how we signal that to SwiftPM.

However, SwiftPM does not shell out to the installed `pkg-config` binary, it attempts to locate the flags itself. So the issue doesn't seem to be that MacPorts is installing its own `pkg-config`, but that SwiftPM is finding a `.pc` file installed by MacPorts for `zlib`.

On macOS the `pkgConfig` directive usually does nothing, and the linking is resolved by the use of the clang module system with the version of `zlib` that ships with the operating system. I will say that the `.pc` file that MacPorts is shipping is dangerous, as it will lead to this same misbehaviour for any tool that attempts to use `pkg-config` to discover its dependencies. As an example of a better behaviour, Homebrew's `.pc` files point to their namespaced package install directories (e.g. `-I/usr/local/Cellar/nghttp2/1.30.0/include`).

We may be able to resolve this by removing the directive unconditionally from macOS builds, but this is not necessarily wise, as users may *want* to use `.pc` files to select an alternative zlib.

**Comment by Lukasa** [comment]
Hang on @moldabekov, are you encountering a consistency issue? The issue originally reported in swift-grpc was that this directive was bringing in header files for unrelated packages, but re-reading your initial comment here seems to suggest that you're getting code built against the header files for MacPorts copy of zlib, but liked against macOS' copy. Is that right?

**Comment by tsabirgaliev** [comment]
@Lukasa do #if macros work in Package.swift?

**Comment by Lukasa** [comment]
They do, but I’m inclined not to want to use it here. Using pkgConfig to override the default macOS installation of zlib is not an unreasonable thing to want to do.

**Comment by tsabirgaliev** [comment]
@Lukasa what about this?

```swift
#if os(macOS)
let package = Package(
    name: "swift-nio-zlib-support")
#else
let package = Package(
    name: "swift-nio-zlib-support",
    pkgConfig: "zlib")
#endif
```

**Comment by Lukasa** [comment]
Yup, that’s what I’m currently not inclined to do. It seems that the problem here is the .pc file MacPorts is placing, not the directive in the Package.swift file.

**Comment by tsabirgaliev** [comment]
@Lukasa can you please elaborate more on this:

> On macOS the pkgConfig directive usually does nothing, and the linking is resolved by the use of the clang module system with the version of zlib that ships with the operating system.

why this is not a problem when I build other software, that links to Macports version of libs?

**Comment by Lukasa** [comment]
It depends entirely on how MacPorts views the world. The problem would only appear if the tools you're building that link MacPorts libraries are a) using `pkg-config`, and b) are trying to only selectively shadow system libraries. I think that's a small number of use-cases to be quite honest, which is why you've likely not hit this issue.

That said, if the output of `pkg-config --cflags zlib` is pointing at a directory with loads of header files in it, this is a problem waiting to happen.

**Comment by jonasmunk** [comment]
I am unable to build Vapor from Xcode because of this issue.
I rely on Macports for many different things so I would like not uninstall it.

Can anyone suggest an easy way to circumvent this problem?

I can manually remove the pkgConfig: "zlib" (https://github.com/apple/swift-nio-zlib-support/blob/master/Package.swift#L23) but it is an indirect dependency so I would have to fork many repos etc.

**Comment by Lukasa** [comment]
The easiest thing to do is probably to set a custom `PKG_CONFIG_PATH` environment variable for your build that excludes all MacPorts `.pc` files.

**Comment by venkatchm** [comment]
> The easiest thing to do is probably to set a custom `PKG_CONFIG_PATH` environment variable for your build that excludes all MacPorts `.pc` files.

How do I do this?

**Comment by weissi** [comment]
@venkatchm you could probably start with an empty `PKG_CONFIG_PATH` and see if that works. To do that, try

```
unset PKG_CONFIG_PATH
swift build
```

there's still a slight chance, that the `pkg-config` from MacPorts picks up MacPorts' `.pc` files because they're in some default location. @venkatchm mind also providing the output of

```
unset PKG_CONFIG_PATH
pkg-config --variable pc_path pkg-config
```

?

**Comment by venkatchm** [comment]
@weissi 
I did unset PKG_CONFIG_PATH. It is still picking up MacPorts' pc files. How do I resolve it?
unset PKG_CONFIG_PATH

> pkg-config --variable pc_path pkg-config

/opt/local/lib/pkgconfig:/opt/local/share/pkgconfig


<img width="1117" alt="Screenshot 2019-09-22 at 11 17 57" src="https://user-images.githubusercontent.com/5646621/65382853-b1088000-dd2a-11e9-9204-2826f04f44a4.png">

**Comment by weissi** [comment]
@venkatchm that is unfortunately what I thought might happen. Right now, I can only see a few options:

- remove the `zlib` pacakge from your installed MacPorts
- `rm -f {/opt/local/lib/pkgconfig,/opt/local/share/pkgconfig}/zlib.pc` to just remove the `zlib.pc` files
- remove the `pkg-config` package from your installed MacPorts
- make sure that SwiftPM doesn't find the MacPorts `pkg-config` binary like so:

```
export PATH="/usr/bin:/bin:/usr/sbin:/sbin"
swift build
```

or (to have it valid only for that one command):

```
PATH="/usr/bin:/bin:/usr/sbin:/sbin" swift build
```

Do those work?

**Comment by venkatchm** [comment]
@weissi It didn't work. 
<img width="1440" alt="Screenshot 2019-09-22 at 17 46 10" src="https://user-images.githubusercontent.com/5646621/65387066-efb92d00-dd60-11e9-95ab-b53ab7d2a911.png">

**Comment by weissi** [comment]
@venkatchm right, so I think we have multiple issues here:
- MacPorts (which I believe we worked around by setting `$PATH`)
- your `/usr/local/include` seems to contain a bunch of headers (such as `/usr/local/include/string.h`) that will cause trouble

For some reason, `/usr/local/include` takes precedence over the SDK (I filed a [bug](https://bugs.swift.org/browse/SR-11504) for this). You seem to have a `string.h` in `/usr/local/include` which will _definitely_ break every build.

If you do not know where the header files in `/usr/local/include` come from, the only thing I can recommend is to delete them all. If you're scared to delete them, you could also do `sudo mv /usr/local/include /usr/local/include-get-out-of-my-way` to just rename it.

**Comment by weissi** [comment]
@venkatchm one thing to confirm would be: Try to open your package with Xcode 11 (needs to be 11) by typing `xed .` inside of your checkout (so from the directory where your `Package.swift` is) and then press Cmd+B to try and build which I believe has a higher chance or working.

**Comment by weissi** [comment]
@venkatchm another option instead of opening in Xcode is to try building it with the Xcode build system from the command line using (again from within your checkout where you'd type `swift build`):

    xcodebuild -scheme swift-nio-Package

you need to replace the `swift-nio` by your package name, so just `MY-PACKAGE-NAME-Package`.

    xcodebuild -scheme $(xcodebuild -list | grep -- -Package$)

should also work

**Comment by weissi** [comment]
@venkatchm so from [SR-11504](https://bugs.swift.org/browse/SR-11504)(thanks @aciidb0mb3r !)  I just learned that the `/usr/local/include` problem goes away if you specify an SDK yourself. So if you just run

    xcrun -sdk macosx swift build

it should work (with `PATH` set as above)

**Comment by Lukasa** [comment]
I believe this should be fine.
